name = "wallet-watcher"
main = "dist/worker.js"
compatibility_date = "2026-02-05"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "BALANCE_STORE"
id = "2c45f0ee511c4cbba7c35d47d0561a68"